ProjectFolder/urls.py
from django.conf.urls import patterns, include, url


# Uncomment the next two lines to enable the admin:
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ProjectFolder.views.home', name='home'),
    # url(r'^ProjectFolder/', include('ProjectFolder.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^preview/', include('template_previewer.urls')),
    #url(r'^templatepreview/', include('previewer.urls')),
    
    url(r'^docreader/', include('docreader.urls',namespace="docreader")),
    url(r'^enersectapp/', include('enersectapp.urls',namespace="enersectapp")),
    url(r'^admin/', include(admin.site.urls)),
)

docreader/urls.py
#This is the nathanapp urls file

from django.conf.urls import patterns, url

from docreader import views

urlpatterns = patterns('',
    

    # ex: /doctoreadtool/
    url(r'^doctoreadtool/$', views.doctoreadtool, name='doctoreadtool'),
    
        
        # ex: /doctoreadtool_savedata/
        url(r'^doctoreadtool_savedata/$', views.doctoreadtool_savedata, name='doctoreadtool_savedata'),
        
        
    
)

enersectapp/urls.py
#This is the enersectapp urls file

from django.conf.urls import patterns, url

from enersectapp import views

urlpatterns = patterns('',

    # Maintenance Screen
    # ex: enersectapp/maintenance_screen
    url(r'^maintenance_screen/$', views.maintenance_screen, name='maintenance_screen'),

    # Note: To access to admin panel, the url is simply /admin
    # Admin already has an authentification mode built in.

    # Main (app_index). Shows the four available modes. Can't access them at the moment
    # ex: /enersectapp/
    url(r'^$', views.main_menu, name='main'),    
        
    # Link User Interface Main.
    # First screen a Link User encounters.
    # Saved for the future, auth purposes or an intro panel.
    # Actual Status: Redirects to Linking Cockpit (Spiderweb)
    # ex: /enersectapp/linkui
    url(r'^linkui/$', views.linkui, name='linkui'),
    
        # Link User Linking Cockpit (Spiderweb). (One Record, explore Pdf Records)
        # Screen with the panels and functions available to the Linking Users.
        # Right side contains the View Panel, that contains a Search By Attributes Search Box,
        # an Arbitrary Values Search, a PDF List, and PDF Visualizer
        # Left side contains the Records Panel, that contains a Search By Attributes Search Box,
        # an Arbitrary Values Search, a PDF List, and PDF Visualizer.
        # It also contains the actions
        # Actual Status: Redirects to Actions
        # ex: /enersectapp/linkui
        url(r'^linkui/spiderweb/$', views.linkui_spiderweb, name='linkui_spiderweb'),
    
    
        # Actual link action (One Record, explore Pdf Records)
        # Assigns the Primary Key of the Unlinked Record to the chosen PDF,
        # in the Foreign Key field.
        # It also changes the "status" of the record to Linked Record
        # Changes the linked_style_class of PdfRecord taken to ui-state-custom-linked (Green color)
        # Then it returns to Spiderweb
        # ex: /enersectapp/5/10/linkui_link
        url(r'^(?P<pdfrecord_id>\d+)/(?P<record_id>\d+)/linkui_link/$', views.linkui_link, name='linkui_link'),
        
        
        # Unlink action (One Record, explore Pdf Records)
        # The opposite of Link action,
        # Changes the error_style_class of the PdfRecord taken
        # to "nolink" (No color)
        
        # Then it returns to Spiderweb
        # ex: /enersectapp/5/linkui_unlink

        url(r'^(?P<pdfrecord_id>\d+)/linkui_unlink/$', views.linkui_unlink, name='linkui_unlink'),
        
        
        # Actual flag action (One Record, explore Pdf Records)
        # Changes the error_style_class of the PdfRecord taken
        # to ui-state-custom-error (Red color)
        # Changes the commentary of the PdfRecord taken
        # to contain "Error detected"
        # Then it returns to Spiderweb
        # ex: /enersectapp/5/10/linkui_link
        url(r'^linkui_flag/$', views.linkui_flag, name='linkui_flag'),
        
        
        # Unflag action (One Record, explore Pdf Records)
        # Changes the error_style_class of the PdfRecord taken
        # to "noerror" (No color)
         # Changes the commentary of the PdfRecord taken
        # to contain "Error solved"
        # Then it returns to Spiderweb
        # ex: /enersectapp/5/10/linkui_link
        url(r'^(?P<pdfrecord_id>\d+)/linkui_unflag/$', views.linkui_unflag, name='linkui_unflag'),
                
        # Skip action in Linking Interface (One Record, explore Pdf Records)
        # Skips the actual Record, putting it at the end of the list
        # ex: /enersectapp/2/skip
        url(r'^(?P<record_id>\d+)/linkui_skip/$', views.linkui_skip, name='linkui_skip'),
        
        
        #-------------------------------------------------------


        # Link User Linking Cockpit (Spiderweb). (One Pdf Record, explore Records)
        # Same as Spiderweb, but with Records in the place of PdfRecords and viceversa
        # ex: /enersectapp/linkui
        url(r'^linkui/spiderweb_viceversa/$', views.linkui_spiderweb_viceversa, name='linkui_spiderweb_viceversa'),
    
    
        # Actual link action (One Pdf Record, explore Records)
        # Same as Spiderweb, but with Records in the place of PdfRecords and viceversa
        # ex: /enersectapp/5/10/linkui_link
        url(r'^(?P<pdfrecord_id>\d+)/(?P<record_id>\d+)/linkui_link/viceversa$', views.linkui_link_viceversa, name='linkui_link_viceversa'),
        
        
        # Unlink action (One Pdf Record, explore Records)
        # Same as Spiderweb, but with Records in the place of PdfRecords and viceversa
        # ex: /enersectapp/5/linkui_unlink

        url(r'^(?P<record_id>\d+)/linkui_unlink/viceversa$', views.linkui_unlink_viceversa, name='linkui_unlink_viceversa'),
        
        
        # Actual flag action (One Pdf Record, explore Records)
        # Same as Spiderweb, but with Records in the place of PdfRecords and viceversa
        # ex: /enersectapp/5/10/linkui_link
        url(r'^linkui_flag/viceversa$', views.linkui_flag_viceversa, name='linkui_flag_viceversa'),
        
        
        # Unflag action (One Pdf Record, explore Records)
        # Same as Spiderweb, but with Records in the place of PdfRecords and viceversa
        # ex: /enersectapp/5/10/linkui_link
        url(r'^(?P<record_id>\d+)/linkui_unflag/viceversa$', views.linkui_unflag_viceversa, name='linkui_unflag_viceversa'),
               
        
        # Skip action in Linking Interface (One Pdf Record, explore Records)
        # Same as Spiderweb, but with Records in the place of PdfRecords and viceversa
        # ex: /enersectapp/2/skip
        url(r'^(?P<pdfrecord_id>\d+)/linkui_skip/viceversa$', views.linkui_skip_viceversa, name='linkui_skip_viceversa'),
        
        

    
        
    #Log In View when not authentificated
    #return redirect('/login/' % request.path)
    #ex: /enersectapp/login/
    url(r'^login/$', views.app_login, name='app_login'),
        
        
        
    # Data Entry Tool Main View, Spider
    # Displays a PDF and lets you choose what kind of Document that is
    # After that is chosen, it displays a form, with all the fields that must be
    # written down so the document is validly passed to the database.
    # A PDF List will be shown up from the server itself, or a chosen folder.
    # This is achieved programming it so it takes the links of those files.
    # When the Data is Submitted validly, it will create an OcrRecord with that
    # data, as well as a PdfRecord that will be linked to that Ocr.
    # It will save in a PdfRecord field that this data was introduced with this tool,
    # as well as the time in which it was created, and who did it.
    # ex: /enersectapp/dataentryui/spider
    url(r'^dataentryui/spider/$', views.dataentryui_spider, name='dataentryui_spider'),
    
        # Data Entry Tool, Save Data function
        # Saves an OcrRecord with the Data provided.
        # Option to pass the data through some filters and comprobations
        # before actually saving them in the database
        # ex: /enersectapp/dataentryui/spider
        url(r'^dataentryui_savedata/$', views.dataentryui_savedata, name='dataentryui_savedata'),
        
        
    # Auth Assign Source Pdfs for Data Entry Utility
        # For Superuser, assigns the selected Source Pdfs to a chosen Team (Company)
        # for Data Entry
        # Adds a SourcePdfToHandle to the field "assigndata" of the chosen Source Pdf's,
        # adding the name of the group/team to the assigned_company field.
        # ex: /admin/enersectapp/sourcepdf/sudo_assign
        url(r'^admin/enersectapp/sourcepdf/sudo_assign/$', views.sudo_assignsourcepdfsui, name='sudo_assignsourcepdfsui'),

    # Auth Assign Source Pdfs for Data Entry Utility
        # For Team Leaders, assigns the selected Source Pdfs to a chosen User in his Team (Company)
        # for Data Entry
        # Adds a SourcePdfToHandle to the field "assigndata" of the chosen Source Pdf's,
        # adding the name of the user to the assigneduser field.
        # ex: /admin/enersectapp/sourcepdf/lead_assign
        url(r'^admin/enersectapp/sourcepdf/lead_assign/$', views.lead_assignsourcepdfsui, name='lead_assignsourcepdfsui'),
        
        
    # Team Leader Interface
        # For Team Leaders, create Users, see the number of records assigned to your company
        # and assign them to different Users
        # When in "Round 2" of the Data Entry, documents will be assigned preferably to different users than
        # the one that made them the first time.
        
        # ex: /admin/enersectapp/teamleaderui/webcocoons
        url(r'^teamleaderui/webcocoons/$', views.webcocoons, name='webcocoons'),
    
        # Team Leader Interface
        # Save the assignations made in the Team Lead Interface
        # This view reorganizes those assignations respective to the number of
        # docs assigned. Will make it through filter()[:X] commands
        # ex: enersectapp/teamleaderui/webcocoons/cocoons_save
        url(r'^teamleaderui/webcocoons/cocoons_save/$', views.cocoons_save, name='cocoons_save'),

    # Team Leader Interface
        # 
        # ex: enersectapp/teamleaderui/webcocoons/cocoons_new_teamuser
        url(r'^teamleaderui/webcocoons/cocoons_new_teamuser/$', views.cocoons_new_teamuser, name='cocoons_new_teamuser'),
     
    
    # QA Spider Random Audit Interface
        # Interface to check if the data entry of random files from a lot was made correctly
        
        url(r'^auditui/randomqa_spider/$', views.randomqa_spider, name='randomqa_spider'), 
        
        
        
    # QA Pair Spider Random Audit Interface
        # Interface to check if the data entry of random files from a lot was made correctly. It audits pairs when available,
        # and has tools for building a third entry.
        
        url(r'^auditui/pair_randomqa_spider/$', views.pair_randomqa_spider, name='pair_randomqa_spider'), 

enersectapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate

from django.shortcuts import get_object_or_404, render, redirect,render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.template import RequestContext
from django.views import generic
from django.utils import timezone
from datetime import timedelta
import datetime
from django.db import transaction
from django.db import connection
import re
import json,csv
from django.core import serializers
import random
from pyPdf import PdfFileWriter, PdfFileReader
from urllib2 import Request, urlopen
from StringIO import StringIO
from django.db.models import Count

from enersectapp.viewsfunctions import (app_index_module,app_login_module,linkui_spiderweb_module,linkui_spiderweb_viceversa_module,dataentryui_spider_module,
                                        pair_randomqa_spider_module,assign_source_pdfs_module,webcocoons_module,randomqa_spider_module,categorization_tool_module,
                                        blank_or_not_blank_module,sudo_assignsourcepdfsui_by_module,progress_report_module,category_changer_module,
                                        arabic_memo_edit_module,search_tool_module,legal_discovery_module,transactions_report_module,transaction_linking_module,
                                        show_transaction_module,add_or_remove_transaction_module,affidavit_generator_module,download_emails_module)

from enersectapp.models import *


def maintenance_screen(request):
  
    return render(request,'enersectapp/maintenance_screen.html',context)

def app_login(request):
  
    return app_login_module.app_login(request)

def main_menu(request):
    
    return app_index_module.app_index(request)

     
def linkui(request):
    return linkui_spiderweb_module.linkui(request)

 
def linkui_spiderweb(request):
    
    return linkui_spiderweb_module.linkui_spiderweb(request)
    
    
def linkui_link(request, pdfrecord_id, record_id):
    
    return linkui_spiderweb_module.linkui_link(request, pdfrecord_id, record_id)


def linkui_unlink(request, pdfrecord_id):
    
    return linkui_spiderweb_module.linkui_unlink(request, pdfrecord_id)
    
def linkui_flag(request):
    
    return linkui_spiderweb_module.linkui_flag(request)   
    
def linkui_unflag(request, pdfrecord_id):
    
    return linkui_spiderweb_module.linkui_unflag(request, pdfrecord_id)   


def linkui_skip(request, record_id):
    
    return linkui_spiderweb_module.linkui_skip(request, record_id)
    

#####---Starts the Linkui view for "Viceversa", when an unlinked Pdf Record is called and multiple Records
# are dynamic

def linkui_spiderweb_viceversa(request):
    
    return linkui_spiderweb_viceversa_module.linkui_spiderweb_viceversa(request)
    
def linkui_link_viceversa(request, pdfrecord_id, record_id):
    
    return linkui_spiderweb_viceversa_module.linkui_link_viceversa(request, pdfrecord_id, record_id)


def linkui_unlink_viceversa(request, record_id):
    
    return linkui_spiderweb_viceversa_module.linkui_unlink_viceversa(request, record_id)  
    
def linkui_flag_viceversa(request):
    
    return linkui_spiderweb_viceversa_module.linkui_flag_viceversa(request)  
    
def linkui_unflag_viceversa(request, record_id):
    
    return linkui_spiderweb_viceversa_module.linkui_unflag_viceversa(request, record_id)      


def linkui_skip_viceversa(request, pdfrecord_id):
    
    return linkui_spiderweb_viceversa_module.linkui_skip_viceversa(request, pdfrecord_id)


def dataentryui_spider(request):
    
    return dataentryui_spider_module.dataentryui_spider(request)

    
def dataentryui_savedata(request):

    return dataentryui_spider_module.dataentryui_savedata(request)


def webcocoons(request):

    return webcocoons_module.webcocoons(request)
    
def cocoons_save(request):

    return webcocoons_module.cocoons_save(request)
    
    
def cocoons_new_teamuser(request):

    return webcocoons_module.cocoons_new_teamuser(request)

def randomqa_spider(request):

    return randomqa_spider_module.randomqa_spider(request)

def pair_randomqa_spider(request):

    return pair_randomqa_spider_module.pair_randomqa_spider(request)
        

def categorization_tool(request):
    
    
    return categorization_tool_module.categorization_tool(request)

    
def blank_or_not_blank(request):

    return blank_or_not_blank_module.blank_or_not_blank(request)

    
def sudo_assignsourcepdfsui_by_doctype_and_number(request):
       
    return sudo_assignsourcepdfsui_by_module.sudo_assignsourcepdfsui_by_doctype_and_number(request)


def progress_report(request):

    return progress_report_module.progress_report(request)

def category_changer(request):

    return category_changer_module.category_changer(request)
    

def arabic_memo_edit(request):
    
    return arabic_memo_edit_module.arabic_memo_edit(request)
    
def search_tool(request):
    
    return search_tool_module.search_tool(request)
    
def legal_discovery(request):
    
    return legal_discovery_module.legal_discovery(request)
    
def transactions_report(request):
    
    return transactions_report_module.transactions_report(request)

def transaction_linking(request):
    
    return transaction_linking_module.transaction_linking(request)    
    
def show_transaction(request,transaction_index):
    
    return show_transaction_module.show_transaction(request,transaction_index)  

    

def add_or_remove_transaction(request,entryId,transactionId,listType,operationType):
    
    return add_or_remove_transaction_module.add_or_remove_transaction(request,entryId,transactionId,listType,operationType) 
    

def affidavit_generator(request):
    return affidavit_generator_module.affidavit_generator(request) 
    
def download_emails(request):
    return download_emails_module.download_emails_interface(request) 
    
    
    
    

###DEPRECATED FUNCTIONS, STILL IN THE SYSTEM THOUGH (WHEN ACCESSING TO THE ASSIGN BUTTON IN THE ADMIN)
  
    
def sudo_assignsourcepdfsui(request):
        
    return assign_source_pdfs_module.sudo_assignsourcepdfsui(request)
    
def lead_assignsourcepdfsui(request):
     
    return assign_source_pdfs_module.lead_assignsourcepdfsui(request)
    
###       

enersectapp/templates/enersectapp/app_login.html
{% load i18n admin_static %}

{% block config_libs %} 

<link rel="stylesheet" type="text/css" href="{% static 'enersectapp/jquery-ui-1.10.3.custom/css/eggplant/jquery-ui-1.10.3.custom.css' %}" />
<script type="text/javascript" src="{% static 'enersectapp/jquery-ui-1.10.3.custom/js/jquery-1.9.1.js' %}" ></script>
<script type="text/javascript" src="{% static 'enersectapp/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.js' %}" ></script>


{% endblock config_libs %}

{% block special_libs %} 
<link rel="stylesheet" type="text/css" href="{% static 'enersectapp/app_login.css' %}" />

{% endblock special_libs %}

{% block javascript %} 

<script>

    $(document).ready(function () {
    
        $( "#login" ).dialog({
          autoOpen: true,
          height: 300,
          width: 350,
          modal: true,
          closeOnEscape: false,
          resizable: false,
          buttons: {
            "Login": function() {
                $('#LoginForm').submit();
            }
          }
          
        });
    
    
    });

</script>

{% endblock javascript %}

{% block content %}
    <div id="login" title="Log In">
        <form id="LoginForm" name="LoginForm" action="{% url 'enersectapp:app_login' %}" method="post">
        {% csrf_token %}
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}" />
        {% endif %}
              
          <fieldset>
            <label for="username">Username</label>
            <input type="text" name="username" id="username"  class="text ui-widget-content ui-corner-all" />
            <label for="password">Password</label>
            <input type="password" name="password" id="password" value="" class="text ui-widget-content ui-corner-all" />
          </fieldset>

        </form>
    </div>
{% endblock %}

enersectapp/templates/enersectapp/blank_or_not_blank.html
{% load i18n %}
{% load staticfiles %}


{% block page_title %}
<head>
{% block special_libs %} 
<link rel="stylesheet" type="text/css" href="{% static 'enersectapp/jquery-ui-1.10.3.custom/css/eggplant/jquery-ui-1.10.3.custom.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'enersectapp/loadingscreen.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'enersectapp/user_panel_module.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'enersectapp/pdf_view_module.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'enersectapp/site_basic_style_template.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'enersectapp/blank_or_not_blank.css' %}" />


{% endblock special_libs %}

{% block config_libs %} 


<script type="text/javascript" src="{% static 'enersectapp/jquery-ui-1.10.3.custom/js/jquery-1.9.1.js' %}" ></script>
<script type="text/javascript" src="{% static 'enersectapp/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.js' %}" ></script>


<script>
    
    $(document).ready(function () {
                
        $('.ui-widget').css("font-size","80%");
        var tips = $( ".validateTips" );
        tips.css("display","none"); 
        
        createPdf_View();
        createUserPanel();
        createFieldsForm();
        configLoadingScreen();

        
        function createPdf_View(){
        
                var $pdf = $('#pdf_view');
            
                var w=$pdf.width();
                var h=$pdf.height();
                       
                var link = $pdf.attr("value");
         
                var s ='<object id="pdf_view_object" data='+link+' type="application/pdf" width="'+w+'" height="'+h+'">';
                s+= 'PDF View not Available in this Browser : ';
                s+= '<a href='+link+'>Alternative Link</a>';
                s+= '</object>'
                
                $pdf.append(s); 
        }
        
        function createUserPanel(){
        
            $( "#user-panel" ).dialog({
                  
                  height: $('#userpanel_container').height(),
                  width: $('#userpanel_container').width(),
                  modal: false,
                  autoOpen:true,
                  closeOnEscape: false,
                  resizable:true,
                  position: {
                    my: "left bottom", at: "left bottom", of: $('#userpanel_container')
                    }
                  
                });
                
                $( "#userpanelmenu" ).menu({ position: { my: "right bottom", at: "right bottom" },
                    select: function( event, ui ) {
                        
                    } 
                });
                
                $('#show_progress_link').click(function(){
                
                    $('#show_progress').attr("value","show_progress");
                    $('#save_id').attr("value","NoId");
                    $('#fields_form').submit();

                });
                
        }
            
        function createFieldsForm(){
        
        
            $( "#dialog-form" ).dialog({
                
                width: $('#fields_container').width(),
                height: $('#fields_container').height(),
                
                modal: false,
                draggable:false,
                resizable: false,
                closeOnEscape: false,
                buttons: {
                    "BLANK": function() {
                        
                        var bValid = true;

                        //allFields.removeClass( "ui-state-error" );
                        $(".ui-state-error").removeClass( "ui-state-error" );
                        
                        $('#blank_or_not_blank').attr('value','blank');
                        
                        $value = $('#blank_or_not_blank').attr('value');
                        
                        if ($value != "other" && $value != "blank" ) bValid = false;

                        if ( bValid ) {
                            
                            toggleLoadingScreen();
                            $('button').attr("disabled", true).addClass("ui-state-disabled");
                            $('#fields_form').submit();
                            
                        }
                    },
                    "NOT BLANK": function() {
                        
                        var bValid = true;

                        //allFields.removeClass( "ui-state-error" );
                        $(".ui-state-error").removeClass( "ui-state-error" );
                        
                        $('#blank_or_not_blank').attr('value','other');
                        
                        $value = $('#blank_or_not_blank').attr('value');
                        
                        if ($value != "other" && $value != "blank" ) bValid = false;
                        
                        if ( bValid ) {
                            
                            toggleLoadingScreen();
                            $('button').attr("disabled", true).addClass("ui-state-disabled");
                            $('#fields_form').submit();
                            
                        }
                    },
                    "UNDO PREVIOUS": function() {
                        
                        var bValid = true;

                        //allFields.removeClass( "ui-state-error" );
                        $(".ui-state-error").removeClass( "ui-state-error" );
                        
                        $('#blank_or_not_blank').attr('value','RollBack');
                        
                        $value = $('#blank_or_not_blank').attr('value');
                        
                        if ($value != "RollBack" ) bValid = false;
                        
                        if ( bValid ) {
                            
                            toggleLoadingScreen();
                            $('button').attr("disabled", true).addClass("ui-state-disabled");
                            $('#fields_form').submit();
                            
                        }
                    },
                    
                },
                position: {
                    my: "left top", at: "left top", of: $('#fields_container')
                }
            });

        }
        
        
        
        function updateTips( t ) {
                  tips
                    .text( t )
                    .addClass( "ui-state-error" );
                    tips.css("display","block");
                  setTimeout(function() {
                    tips.removeClass( "ui-state-error", 1500 );
                    tips.css("display","none");
                  }, 5000 );
        }
       
        function configLoadingScreen(){
        
            image_width = $('#LoadingSpinner').width();
            image_height = $('#LoadingSpinner').height();
            
            $('#LoadingSpinner').css("margin-left",-image_width/2);
            $('#LoadingSpinner').css("margin-top",-image_height/2);
            
            //text_width = $('#LoadingDescription').width();
            //text_height = $('#LoadingDescription').height();
        
            //$('#LoadingDescription').css("margin-left",-text_width/2);
            //$('#LoadingDescription').css("margin-top",-text_height/2);

        }
        
        function toggleLoadingScreen(){
        
            $('#LoadingScreen').toggleClass("invisible");
            
        }
       
        
        
    });
        
</script>
{% endblock config_libs %}

<title>Blank Or Not Blank Tool Interface</title>

</head>
{% endblock page_title %}





{% block jqueryui_setups %}



{% endblock jqueryui_setups %}  

<body>
{% if not is_popup %}

{% block container_all %}

<div id = "LoadingScreen" class="invisible">
        <img id ="LoadingSpinner"  src = "{% static 'enersectapp/images/ajax-loader.gif' %}"/>
        <h4 id="LoadingDescription"></h4>
</div>


<div id="container_all">

{% block container_headers %}

<div id="container_headers">



</div>

{% endblock container_headers %}

{% block container_body %}

<div id="container_body">


{% block content%}
    
    {% if chosen_item %}
    
    
    <div id="left_container">
    
        <div id="fields_container">
        
            <div id="dialog-form" title="Assign New Document Type">
                            
                <p class="validateTips">Selecting or Adding a Document Type is Required.</p>
             
                <form id="fields_form" autocomplete="off" action="{% url 'enersectapp:blank_or_not_blank' %}" method="post">
                {% csrf_token %}
               
                <input class="invisible" type="text" name="blank_or_not_blank" id="blank_or_not_blank" value="" />
                <input class="invisible" type="text" name="save_id" id="save_id" value="{{chosen_item.id}}" />
         
                <input class="invisible" type="text" name="show_progress" id="show_progress" value="" />
                

                <h3>{{success_message}}</h3>
                
                </form>
            </div>
            
        </div>
        
    </div>
    {% endif%}
    <div id="right_container">
        
            
        <div id="pdf_view" value="http:\\54.200.180.182\sourcepdfs\{{chosen_item.job_directory}}\{{chosen_item.filename}}">
        
        
        </div>
        
        
        <div id="userpanel_container">
            <div id="user-panel" title="{{the_user}}">
                
                <p class="validateTips_Countdown">{{show_progress_user}} <br><br> Probable Blanks left in this Mode: {{count_blank_probable}}</p>

                <ul class="menuclass" id="userpanelmenu">
                    <!--<li><a id="show_progress_link" href="#">Show Progress</a></li>
                    <li>--</li>-->
                    <li><a id="logout_link" href="{% url 'enersectapp:app_login' %}">Change User</a></li>
                    <li>--</li>
                    <li><a id="toolsmenu_link" href="{% url 'enersectapp:main' %}">Return to Tools Menu</a></li>
                </ul>
            </div>
        </div>
                
    </div>
   

    
{% endblock content%}



</div>

{% endblock container_body %}

</div>

{% endblock container_all %}

{% endif %}
</body>


{% block sidebar %}{% endblock %}

enersectapp/templates/enersectapp/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>